[project]
name = "network-graph-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "networkx>=3.6.1",
    "pandas>=3.0.1",
    "pandas-stubs>=3.0.0.260204",
    "pyvis>=0.3.2",
    "streamlit>=1.19.0",
]
